name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # Linux build
      - name: Build Linux app
        if: matrix.os == 'ubuntu-latest'
        run: yarn electron-builder --linux --publish=never

      # Windows build
      - name: Build Windows app
        if: matrix.os == 'windows-latest'
        run: yarn electron-builder --windows --publish=never

      # macOS build with signing
      - name: Decode signing cert
        if: matrix.os == 'macos-latest'
        run: echo "$MAC_CERT_P12" | base64 --decode > cert.p12
        shell: bash

      - name: Import signing cert
        if: matrix.os == 'macos-latest'
        run: |
          security create-keychain -p "" build.keychain
          security import cert.p12 -k ~/Library/Keychains/build.keychain -P "$MAC_CERT_PASSWORD" -T /usr/bin/codesign -T /usr/bin/productsign
          security set-keychain-settings -lut 21600 build.keychain
          security list-keychains -s build.keychain
          security unlock-keychain -p "" build.keychain
        shell: bash

      - name: Build macOS app
        if: matrix.os == 'macos-latest'
        run: yarn electron-builder --mac --publish=never
        env:
          CSC_LINK: cert.p12
          CSC_KEY_PASSWORD: ${{ secrets.MAC_CERT_PASSWORD }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-build
          path: dist/
          
  create-release:
    needs: release
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist/
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/**/*.dmg
            dist/**/*.exe
            dist/**/*.AppImage
            dist/**/*.deb
            dist/**/*.zip
            dist/**/latest-mac.yml
            dist/**/latest-linux.yml
            dist/**/latest.yml
          draft: false
          prerelease: false
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: TOPIN-Companion-${{ matrix.os }}
          path: dist/**
